### ISSUE TITLE
sysinfo-snapshot-3.5.0 and later does not work on FIPS enabled systems.

### ISSUE THREAD

**Issue by bviviano** [Mellanox/linux-sysinfo-snapshot#1]
sysinfo-snapshot 3.5.0 and later calls:

ibnetdiscover_output_hashed = hashlib.md5(ibnetdiscover_output.encode('utf-8')).hexdigest()

Which fails on any FIPS enabled system.

**Comment by ananfa12** [comment]
Hi, 

Thank you for your feedback, we fixed the issue in the latest release - v3.6.1
https://github.com/Mellanox/linux-sysinfo-snapshot/releases/tag/v3.6.1

We changed the md5 hashing to sha256 hashing
