### ISSUE TITLE
The sysinfo-snapshot release 3.7.7 reports version as 3.7.6.

### ISSUE THREAD

**Issue by markhaywood** [Mellanox/linux-sysinfo-snapshot#8]
$ sysinfo-snapshot.py -v
Sysinfo-snapshot version: 3.7.6

After pulling the v3.7.7 tag, I inspected the sysinfo-snapshot.py source and at line 73 found:

version = "3.7.6"

I mention this because I see a subsequent patch to the master and latest branches have incremented the version:

https://github.com/Mellanox/linux-sysinfo-snapshot/commit/aa329217479a40870de8b939c803c708fbc4d214

version = "3.7.7"

So, is the v3.7.7 tag incorrect? It appears that it is.

**Comment by lamad23** [comment]
fixed the issue with the release tag should be updated now
